CREATE DATABASE BAI1
GO
USE BAI1
GO

CREATE TABLE KHACHHANG(
    MAKH CHAR(6) NOT NULL,
    HOTEN NVARCHAR(50),
    SODIENTHOAI INT,
    COQUAN NVARCHAR(100)
)
ALTER TABLE KHACHHANG ADD CONSTRAINT pk_khachhang PRIMARY KEY(MAKH)

CREATE TABLE NHACHOTHUE(
    MAN CHAR(6) NOT NULL,
    DIACHI NVARCHAR(100),
    GIATHUE INT,
    TENCHUNHA NVARCHAR(50)
)
ALTER TABLE NHACHOTHUE ADD CONSTRAINT pk_nhachothue PRIMARY KEY(MAN)

CREATE TABLE HOPDONG(
    MAN CHAR(6) NOT NULL,
    MAKH CHAR(6) NOT NULL,
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE
)
ALTER TABLE HOPDONG ADD CONSTRAINT pk_hopdong PRIMARY KEY(MAN, MAKH)
ALTER TABLE HOPDONG ADD CONSTRAINT fk_hopdong_khachhang FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE HOPDONG ADD CONSTRAINT fk_hopdong_nhachothue FOREIGN KEY(MAN) REFERENCES NHACHOTHUE(MAN)

-- a
SELECT DIACHI, TENCHUNHA FROM NHACHOTHUE WHERE GIATHUE < 10000000

-- b
SELECT MAKH, HOTEN, COQUAN FROM KHACHHANG
WHERE MAKH IN (
    SELECT MAKH FROM HOPDONG
    WHERE MAN IN (SELECT MAN FROM NHACHOTHUE WHERE TENCHUNHA LIKE N'Nông Văn Diền')
)

-- c
SELECT * FROM NHACHOTHUE
WHERE MAN NOT IN (
    SELECT MAN FROM HOPDONG
)

-- d
SELECT TOP 1 GIATHUE FROM NHACHOTHUE
WHERE MAN IN (
    SELECT MAN FROM HOPDONG
)
ORDER BY GIATHUE DESC